##########################
#
#########################
hostname: node1
###########################
#定义IP地址
###########################
local_ip: 192.168.137.37
remote_ip: 192.168.137.38
local_port: 18000
remote_port: 18000
############################
#log日志定义
############################
say_hello_log:
  say_hello: "/tmp/say_hello_m.log"
###########################
# 定义vip(可以飘移)
###########################
vip: 192.168.137.85
vip_netmask: 24
vip_dev: "eth0"
vip_gw: "192.168.137.1"
vip_role: master
############################
#   延迟设定,注意这里必须是整数
############################
#初始尝试互联重试延迟
init_connect_delay: 1
#发送hello消息延迟
say_hello_delay: 0.1
#包发送检查延迟
packet_send_check_delay: 1
#发送say_hello失败重试的次数
say_hello_fails_retry: 2
#发送hello消息后，等待对方回应的最长时间
say_hello_max_timeout: 1
